# Generated by Django 5.0.1 on 2024-02-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comments_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='api.posts'),
        ),
    ]
