# Generated by Django 5.0.1 on 2024-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comments_id_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='post_images/'),
        ),
    ]
