# Generated by Django 5.0.1 on 2024-02-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_comments_replies_remove_posts_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='posts',
            name='comment_counter',
            field=models.IntegerField(default=0),
        ),
    ]
