# Generated by Django 5.0.1 on 2024-02-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_posts_liked_by_posts_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to='api.comments'),
        ),
    ]
