# Generated by Django 5.0.1 on 2024-02-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_posts_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='interests',
            field=models.TextField(default='', max_length=50, null=True),
        ),
    ]
