# Generated by Django 5.0.1 on 2024-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_users_about_alter_users_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
