# Generated by Django 5.0.1 on 2024-02-09 17:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_users_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(default='')),
                ('departure', models.DateTimeField(default=datetime.datetime(2024, 2, 9, 17, 11, 42, 904201, tzinfo=datetime.timezone.utc))),
                ('arrival', models.DateTimeField(default='')),
                ('denial_reason', models.TextField(default='')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_forms', to='api.users')),
                ('warden', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_leaves', to='api.users')),
            ],
        ),
    ]
